# fly.toml app configuration file generated for drugx on 2026-04-08T13:12:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drugx'
primary_region = 'cdg'

[build]

[env]
  PYTHONPATH = '/app'
  STREAMLIT_BROWSER_GATHER_USAGE_STATS = 'false'
  STREAMLIT_SERVER_HEADLESS = 'true'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
