name: Code quality CI

on:
  push:
    branches: ["feature-**", "dev", "main"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/**"
  pull_request:
    branches: [main, dev]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  lint:
    name: Python Code Quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Run Ruff checks
      run: |
        uvx ruff check .
        uvx ruff format --check .

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - id: py
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Run unit tests
        run: |
          mkdir -p reports
          set -euo pipefail
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            uv run --isolated --with pytest --with pytest-asyncio --with pytest-cov pytest tests --cov=src --cov-report=term-missing | tee reports/coverage.txt
          else
            uv run --isolated --with pytest --with pytest-asyncio pytest tests
          fi

      - name: Upload coverage report
        if: ${{ !env.ACT && github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: reports/coverage.txt
